name: Test workflow

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        node: [ '12', '14' ]
        operating-system: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run lint
      - run: npm run bootstrap
      - run: npm run build
      - run: npm test
